const Data = [
    {
        id: 1,
        name: '최현진',
        type: '프론트엔드',
        skill: ['React', 'JavaScript', '', ''],
        content:
            '안녕하세요! 공공데이터 공모전 팀에 지원하게 된 김지은입니다. 저는 데이터 사이언스 과목을 수강하며 데이터에 관한 기본적인 내용들을 배우며 이런 데이터를 잘 활용하고, 이용하는 것이 중요한 역량이 될 것 같다고 판단했습니다. 그래서 관련된 역량을 쌓고자 공모전에 출품하고 싶다는 생각을 가지게 되었고, 공공데이터 공모전이 적합하다고 생각했습니다! 회의 지역이 저희 학교 근처이고, 성실함이 무기인 팀원을 찾고 계신다고 하셔서 지원하게 되었습니다.',
        open: false,
    },
    {
        id: 2,
        name: '원채영',
        type: '프론트엔드',
        skill: ['React', 'JavaScript', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 3,
        name: '최수빈',
        type: '프론트엔드',
        skill: ['React', 'JavaScript', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 4,
        name: '이한슬',
        type: '프론트엔드',
        skill: ['React', 'JavaScript', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 5,
        name: '김지은',
        type: '프론트엔드',
        skill: ['', 'JavaScript', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 6,
        name: '한진우',
        type: '프론트엔드',
        skill: ['React', '', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 7,
        name: '김지은',
        type: '프론트엔드',
        skill: ['', 'JavaScript', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 8,
        name: '한진우',
        type: '프론트엔드',
        skill: ['React', '', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 9,
        name: '김지은',
        type: '프론트엔드',
        skill: ['', 'JavaScript', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 10,
        name: '한진우',
        type: '프론트엔드',
        skill: ['React', '', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 11,
        name: '김지은',
        type: '프론트엔드',
        skill: ['', 'JavaScript', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 12,
        name: '한진우',
        type: '프론트엔드',
        skill: ['React', '', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 13,
        name: '김지은',
        type: '프론트엔드',
        skill: ['', 'JavaScript', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 14,
        name: '한진우',
        type: '프론트엔드',
        skill: ['React', '', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 15,
        name: '김지은',
        type: '프론트엔드',
        skill: ['', 'JavaScript', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 16,
        name: '한진우',
        type: '프론트엔드',
        skill: ['React', '', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 17,
        name: '김지은',
        type: '프론트엔드',
        skill: ['', 'JavaScript', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 18,
        name: '한진우',
        type: '프론트엔드',
        skill: ['React', '', '', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 19,
        name: '이정진',
        type: '백엔드',
        skill: ['', '', 'Spring', 'Node.js'],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 20,
        name: '이서영',
        type: '백엔드',
        skill: ['', '', 'Spring', 'Node.js'],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: true,
    },
    {
        id: 21,
        name: '염지은',
        type: '백엔드',
        skill: ['', '', 'Spring', ''],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: false,
    },
    {
        id: 22,
        name: '김진영',
        type: '백엔드',
        skill: ['', '', '', 'Node.js'],
        content: '저는 자신있습니다! 열심히 하겠습니다!',
        open: true,
    },
];

const Fields = ['프론트엔드', '백엔드'];
const Skills = ['React', 'JavaScript', 'Spring', 'Node.js'];

export { Data, Fields, Skills };
